spring:
  application:
    name: ms-permission-registry

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/consent_manager}
    username: ${DB_USERNAME:consent_admin}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  cache:
    type: redis
    redis:
      time-to-live: 3600000

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ms-permission-registry
